### ISSUE TITLE
As a team member, I need to create a UI Flow Diagram, so I can understand the high-level relationships between major user interface elements, and ask fundamental usability questions

### ISSUE THREAD

**Issue by david-gay** [david-gay/2340#22]
Create a UI flow diagram as shown in class that plans for the navigation of the screens required for the application. Also, the team should have a prototype (sketches) of the major screens in the application.
* You can use automated tool like FluidUI for this if desired.

**Comment by mitelinko** [comment]
The UI flow has been done with FluidUI. It can be viewed [here](https://www.fluidui.com/editor/live/livePreview/cF84SzMzeTRlNGwwcE5xd1VpOVZpbHlEVERXUkcySEdiRA==)
