### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by david-gay** [david-gay/2340#3]
Go to the Post Final Project Teams Here page on the wiki and:

Add your name and email to the Team Page on the wiki.
- [ ] @david-gay 
- [x] @mitelinko 
- [x] @blake-harper 
- [x] @kellerw 
- [x] suzil

1. Make a page for our glorious team
2. Establish incredible team name and include original team number in parentheses
3. Enter team email addresses
4. Link to GitHub page
5. Other information as desired

**Comment by suzil** [comment]
Before we can create a team page, we'll have to agree on a name.

**Comment by david-gay** [comment]
Thoughts on UGA go away?

**Comment by suzil** [comment]
I'm fine with that name. How about @kellerw @blake-harper @mitelinko ?

**Comment by mitelinko** [comment]
It's recursive. I like it!

**Comment by blake-harper** [comment]
I like the idea and would be fine with it ending up with that, but I think we can hold ourselves to a higher standard of cleverness.
