### ISSUE TITLE
Project Planning

### ISSUE THREAD

**Issue by david-gay** [david-gay/2340#5]
1. Create a GitHub public repository
2. Create Milestones every 4 weeks for the project. Name them Sprint 1, Sprint 2, etc.
3. Create issues that outline tasks for the next 3 milestones (M2, M3, M4) in the project
4. Create Labels named Feature and Support
5. Assign Appropriate label to each issue
6. Estimate the issues and assign them to Sprint 1

**Comment by suzil** [comment]
> Create Milestones every 4 weeks for the project. Name them Sprint 1, Sprint 2, etc.
> Create issues that outline tasks for the next 3 milestones (M2, M3, M4) in the project

I believe that we're meant to create all 12 milestones instead of just the 3; so, I think our current setup is right. It makes more sense to do the 12.
